import Navigation from "@/components/Navigation";
import "./globals.css";
import Container from "@/components/Container";
import { Footer } from "@/components/Footer";
import style from "../components/slideBar.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${style.contenedorScroll}`}>
        <Container>
          <Navigation />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
