import Navigation from "@/components/Navigation";
import "./globals.css";
import Container from "@/components/Container";
import { Footer } from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Navigation />
          {children}
          <Footer/>
        </Container>
      </body>
    </html>
  );
}
